// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'940ae0f097a9ce638e8b6d0e6590a8cb93a34222fbd6ba8ff7c5dfa8bbef7267'>;
export type ExecutionHash =
  ExecutionHashBase<'3d0095330e40ac07d2ac50355f4b5b8f4d51d8372e0a1ee92345287b32227a1d'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly DemoAccount: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
      readonly accountNumber: CodecTypes['pg/text@1']['output'];
      readonly currency: CodecTypes['pg/text@1']['output'];
      readonly initialBalance: CodecTypes['pg/numeric@1']['output'];
      readonly balance: CodecTypes['pg/numeric@1']['output'];
      readonly equity: CodecTypes['pg/numeric@1']['output'];
      readonly status: 'ACTIVE' | 'SUSPENDED' | 'CLOSED';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly MarketPrice: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly symbol: CodecTypes['pg/text@1']['output'];
      readonly bid: CodecTypes['pg/numeric@1']['output'];
      readonly ask: CodecTypes['pg/numeric@1']['output'];
      readonly last: CodecTypes['pg/numeric@1']['output'];
      readonly source: CodecTypes['pg/text@1']['output'] | null;
      readonly timestamp: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Order: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly accountId: CodecTypes['pg/text@1']['output'];
      readonly symbol: CodecTypes['pg/text@1']['output'];
      readonly side: 'BUY' | 'SELL';
      readonly orderType: 'MARKET';
      readonly quantity: CodecTypes['pg/numeric@1']['output'];
      readonly requestedPrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly executedPrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly status: 'PENDING' | 'FILLED' | 'REJECTED' | 'CANCELLED';
      readonly commission: CodecTypes['pg/numeric@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly executedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    };
    readonly Position: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly accountId: CodecTypes['pg/text@1']['output'];
      readonly symbol: CodecTypes['pg/text@1']['output'];
      readonly side: 'LONG' | 'SHORT';
      readonly quantity: CodecTypes['pg/numeric@1']['output'];
      readonly averageEntryPrice: CodecTypes['pg/numeric@1']['output'];
      readonly currentPrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly unrealizedPnl: CodecTypes['pg/numeric@1']['output'];
      readonly status: 'OPEN' | 'CLOSED';
      readonly openedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly closedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    };
    readonly Trade: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly accountId: CodecTypes['pg/text@1']['output'];
      readonly orderId: CodecTypes['pg/text@1']['output'];
      readonly positionId: CodecTypes['pg/text@1']['output'] | null;
      readonly symbol: CodecTypes['pg/text@1']['output'];
      readonly side: 'BUY' | 'SELL';
      readonly quantity: CodecTypes['pg/numeric@1']['output'];
      readonly entryPrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly exitPrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly realizedPnl: CodecTypes['pg/numeric@1']['output'] | null;
      readonly commission: CodecTypes['pg/numeric@1']['output'];
      readonly openedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly closedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    };
    readonly User: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
      readonly fullName: CodecTypes['pg/text@1']['output'] | null;
      readonly role: 'USER' | 'ADMIN';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly DemoAccount: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
      readonly accountNumber: CodecTypes['pg/text@1']['input'];
      readonly currency: CodecTypes['pg/text@1']['input'];
      readonly initialBalance: CodecTypes['pg/numeric@1']['input'];
      readonly balance: CodecTypes['pg/numeric@1']['input'];
      readonly equity: CodecTypes['pg/numeric@1']['input'];
      readonly status: 'ACTIVE' | 'SUSPENDED' | 'CLOSED';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly MarketPrice: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly symbol: CodecTypes['pg/text@1']['input'];
      readonly bid: CodecTypes['pg/numeric@1']['input'];
      readonly ask: CodecTypes['pg/numeric@1']['input'];
      readonly last: CodecTypes['pg/numeric@1']['input'];
      readonly source: CodecTypes['pg/text@1']['input'] | null;
      readonly timestamp: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Order: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly accountId: CodecTypes['pg/text@1']['input'];
      readonly symbol: CodecTypes['pg/text@1']['input'];
      readonly side: 'BUY' | 'SELL';
      readonly orderType: 'MARKET';
      readonly quantity: CodecTypes['pg/numeric@1']['input'];
      readonly requestedPrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly executedPrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly status: 'PENDING' | 'FILLED' | 'REJECTED' | 'CANCELLED';
      readonly commission: CodecTypes['pg/numeric@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly executedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
    };
    readonly Position: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly accountId: CodecTypes['pg/text@1']['input'];
      readonly symbol: CodecTypes['pg/text@1']['input'];
      readonly side: 'LONG' | 'SHORT';
      readonly quantity: CodecTypes['pg/numeric@1']['input'];
      readonly averageEntryPrice: CodecTypes['pg/numeric@1']['input'];
      readonly currentPrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly unrealizedPnl: CodecTypes['pg/numeric@1']['input'];
      readonly status: 'OPEN' | 'CLOSED';
      readonly openedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly closedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
    };
    readonly Trade: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly accountId: CodecTypes['pg/text@1']['input'];
      readonly orderId: CodecTypes['pg/text@1']['input'];
      readonly positionId: CodecTypes['pg/text@1']['input'] | null;
      readonly symbol: CodecTypes['pg/text@1']['input'];
      readonly side: 'BUY' | 'SELL';
      readonly quantity: CodecTypes['pg/numeric@1']['input'];
      readonly entryPrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly exitPrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly realizedPnl: CodecTypes['pg/numeric@1']['input'] | null;
      readonly commission: CodecTypes['pg/numeric@1']['input'];
      readonly openedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly closedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
    };
    readonly User: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
      readonly fullName: CodecTypes['pg/text@1']['input'] | null;
      readonly role: 'USER' | 'ADMIN';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly demoAccount: {
      readonly accountNumber: CodecTypes['pg/text@1']['output'];
      readonly balance: CodecTypes['pg/numeric@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly currency: CodecTypes['pg/text@1']['output'];
      readonly equity: CodecTypes['pg/numeric@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly initialBalance: CodecTypes['pg/numeric@1']['output'];
      readonly status: 'ACTIVE' | 'SUSPENDED' | 'CLOSED';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly marketPrice: {
      readonly ask: CodecTypes['pg/numeric@1']['output'];
      readonly bid: CodecTypes['pg/numeric@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly last: CodecTypes['pg/numeric@1']['output'];
      readonly source: CodecTypes['pg/text@1']['output'] | null;
      readonly symbol: CodecTypes['pg/text@1']['output'];
      readonly timestamp: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly order: {
      readonly accountId: CodecTypes['pg/text@1']['output'];
      readonly commission: CodecTypes['pg/numeric@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly executedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly executedPrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly orderType: 'MARKET';
      readonly quantity: CodecTypes['pg/numeric@1']['output'];
      readonly requestedPrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly side: 'BUY' | 'SELL';
      readonly status: 'PENDING' | 'FILLED' | 'REJECTED' | 'CANCELLED';
      readonly symbol: CodecTypes['pg/text@1']['output'];
    };
    readonly position: {
      readonly accountId: CodecTypes['pg/text@1']['output'];
      readonly averageEntryPrice: CodecTypes['pg/numeric@1']['output'];
      readonly closedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly currentPrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly openedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly quantity: CodecTypes['pg/numeric@1']['output'];
      readonly side: 'LONG' | 'SHORT';
      readonly status: 'OPEN' | 'CLOSED';
      readonly symbol: CodecTypes['pg/text@1']['output'];
      readonly unrealizedPnl: CodecTypes['pg/numeric@1']['output'];
    };
    readonly trade: {
      readonly accountId: CodecTypes['pg/text@1']['output'];
      readonly closedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly commission: CodecTypes['pg/numeric@1']['output'];
      readonly entryPrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly exitPrice: CodecTypes['pg/numeric@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly openedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly orderId: CodecTypes['pg/text@1']['output'];
      readonly positionId: CodecTypes['pg/text@1']['output'] | null;
      readonly quantity: CodecTypes['pg/numeric@1']['output'];
      readonly realizedPnl: CodecTypes['pg/numeric@1']['output'] | null;
      readonly side: 'BUY' | 'SELL';
      readonly symbol: CodecTypes['pg/text@1']['output'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly fullName: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
      readonly role: 'USER' | 'ADMIN';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly demoAccount: {
      readonly accountNumber: CodecTypes['pg/text@1']['input'];
      readonly balance: CodecTypes['pg/numeric@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly currency: CodecTypes['pg/text@1']['input'];
      readonly equity: CodecTypes['pg/numeric@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly initialBalance: CodecTypes['pg/numeric@1']['input'];
      readonly status: 'ACTIVE' | 'SUSPENDED' | 'CLOSED';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly marketPrice: {
      readonly ask: CodecTypes['pg/numeric@1']['input'];
      readonly bid: CodecTypes['pg/numeric@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly last: CodecTypes['pg/numeric@1']['input'];
      readonly source: CodecTypes['pg/text@1']['input'] | null;
      readonly symbol: CodecTypes['pg/text@1']['input'];
      readonly timestamp: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly order: {
      readonly accountId: CodecTypes['pg/text@1']['input'];
      readonly commission: CodecTypes['pg/numeric@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly executedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly executedPrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly orderType: 'MARKET';
      readonly quantity: CodecTypes['pg/numeric@1']['input'];
      readonly requestedPrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly side: 'BUY' | 'SELL';
      readonly status: 'PENDING' | 'FILLED' | 'REJECTED' | 'CANCELLED';
      readonly symbol: CodecTypes['pg/text@1']['input'];
    };
    readonly position: {
      readonly accountId: CodecTypes['pg/text@1']['input'];
      readonly averageEntryPrice: CodecTypes['pg/numeric@1']['input'];
      readonly closedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly currentPrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly openedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly quantity: CodecTypes['pg/numeric@1']['input'];
      readonly side: 'LONG' | 'SHORT';
      readonly status: 'OPEN' | 'CLOSED';
      readonly symbol: CodecTypes['pg/text@1']['input'];
      readonly unrealizedPnl: CodecTypes['pg/numeric@1']['input'];
    };
    readonly trade: {
      readonly accountId: CodecTypes['pg/text@1']['input'];
      readonly closedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly commission: CodecTypes['pg/numeric@1']['input'];
      readonly entryPrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly exitPrice: CodecTypes['pg/numeric@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly openedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly orderId: CodecTypes['pg/text@1']['input'];
      readonly positionId: CodecTypes['pg/text@1']['input'] | null;
      readonly quantity: CodecTypes['pg/numeric@1']['input'];
      readonly realizedPnl: CodecTypes['pg/numeric@1']['input'] | null;
      readonly side: 'BUY' | 'SELL';
      readonly symbol: CodecTypes['pg/text@1']['input'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly fullName: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
      readonly role: 'USER' | 'ADMIN';
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};

export namespace Models {
  export type public_User = {
    id: CodecTypes['pg/text@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    passwordHash: CodecTypes['pg/text@1']['output'];
    fullName: CodecTypes['pg/text@1']['output'] | null;
    role: 'USER' | 'ADMIN';
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    demoAccounts: public_DemoAccount[];
    readonly [RelationKeys]?: 'demoAccounts';
  };
  export type public_DemoAccount = {
    id: CodecTypes['pg/text@1']['output'];
    userId: CodecTypes['pg/text@1']['output'];
    accountNumber: CodecTypes['pg/text@1']['output'];
    currency: CodecTypes['pg/text@1']['output'];
    initialBalance: CodecTypes['pg/numeric@1']['output'];
    balance: CodecTypes['pg/numeric@1']['output'];
    equity: CodecTypes['pg/numeric@1']['output'];
    status: 'ACTIVE' | 'SUSPENDED' | 'CLOSED';
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    orders: public_Order[];
    positions: public_Position[];
    trades: public_Trade[];
    user: public_User;
    readonly [RelationKeys]?: 'orders' | 'positions' | 'trades' | 'user';
  };
  export type public_MarketPrice = {
    id: CodecTypes['pg/text@1']['output'];
    symbol: CodecTypes['pg/text@1']['output'];
    bid: CodecTypes['pg/numeric@1']['output'];
    ask: CodecTypes['pg/numeric@1']['output'];
    last: CodecTypes['pg/numeric@1']['output'];
    source: CodecTypes['pg/text@1']['output'] | null;
    timestamp: CodecTypes['pg/timestamptz-string@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_Order = {
    id: CodecTypes['pg/text@1']['output'];
    accountId: CodecTypes['pg/text@1']['output'];
    symbol: CodecTypes['pg/text@1']['output'];
    side: 'BUY' | 'SELL';
    orderType: 'MARKET';
    quantity: CodecTypes['pg/numeric@1']['output'];
    requestedPrice: CodecTypes['pg/numeric@1']['output'] | null;
    executedPrice: CodecTypes['pg/numeric@1']['output'] | null;
    status: 'PENDING' | 'FILLED' | 'REJECTED' | 'CANCELLED';
    commission: CodecTypes['pg/numeric@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    executedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    account: public_DemoAccount;
    trades: public_Trade[];
    readonly [RelationKeys]?: 'account' | 'trades';
  };
  export type public_Position = {
    id: CodecTypes['pg/text@1']['output'];
    accountId: CodecTypes['pg/text@1']['output'];
    symbol: CodecTypes['pg/text@1']['output'];
    side: 'LONG' | 'SHORT';
    quantity: CodecTypes['pg/numeric@1']['output'];
    averageEntryPrice: CodecTypes['pg/numeric@1']['output'];
    currentPrice: CodecTypes['pg/numeric@1']['output'] | null;
    unrealizedPnl: CodecTypes['pg/numeric@1']['output'];
    status: 'OPEN' | 'CLOSED';
    openedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    closedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    account: public_DemoAccount;
    trades: public_Trade[];
    readonly [RelationKeys]?: 'account' | 'trades';
  };
  export type public_Trade = {
    id: CodecTypes['pg/text@1']['output'];
    accountId: CodecTypes['pg/text@1']['output'];
    orderId: CodecTypes['pg/text@1']['output'];
    positionId: CodecTypes['pg/text@1']['output'] | null;
    symbol: CodecTypes['pg/text@1']['output'];
    side: 'BUY' | 'SELL';
    quantity: CodecTypes['pg/numeric@1']['output'];
    entryPrice: CodecTypes['pg/numeric@1']['output'] | null;
    exitPrice: CodecTypes['pg/numeric@1']['output'] | null;
    realizedPnl: CodecTypes['pg/numeric@1']['output'] | null;
    commission: CodecTypes['pg/numeric@1']['output'];
    openedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    closedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    account: public_DemoAccount;
    order: public_Order;
    position: public_Position | null;
    readonly [RelationKeys]?: 'account' | 'order' | 'position';
  };
}

export declare const models: {
  public: {
    User: Models.public_User;
    DemoAccount: Models.public_DemoAccount;
    MarketPrice: Models.public_MarketPrice;
    Order: Models.public_Order;
    Position: Models.public_Position;
    Trade: Models.public_Trade;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly demoAccount: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly accountNumber: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly currency: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'USD'>;
                  };
                };
                readonly initialBalance: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly balance: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly equity: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'ACTIVE'>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['accountNumber'] }];
              indexes: readonly [
                {
                  readonly name: 'demoAccount_userId_idx_a489d58a';
                  readonly prefix: 'demoAccount_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'demoAccount';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly marketPrice: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly symbol: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly bid: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly ask: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly last: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly source: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly timestamp: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'marketPrice_symbol_timestamp_idx_524ddd3c';
                  readonly prefix: 'marketPrice_symbol_timestamp_idx';
                  readonly columns: readonly ['symbol', 'timestamp'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly order: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly accountId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly symbol: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly side: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly orderType: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'MARKET'>;
                  };
                };
                readonly quantity: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly requestedPrice: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly executedPrice: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                };
                readonly commission: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly executedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'order_accountId_createdAt_idx_843b5d93';
                  readonly prefix: 'order_accountId_createdAt_idx';
                  readonly columns: readonly ['accountId', 'createdAt'];
                  readonly unique: false;
                },
                {
                  readonly name: 'order_accountId_idx_cbfb3085';
                  readonly prefix: 'order_accountId_idx';
                  readonly columns: readonly ['accountId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'order';
                    readonly columns: readonly ['accountId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'demoAccount';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly position: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly accountId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly symbol: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly side: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly quantity: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly averageEntryPrice: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly currentPrice: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly unrealizedPnl: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'OPEN'>;
                  };
                };
                readonly openedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly closedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'position_accountId_status_idx_ed560107';
                  readonly prefix: 'position_accountId_status_idx';
                  readonly columns: readonly ['accountId', 'status'];
                  readonly unique: false;
                },
                {
                  readonly name: 'position_symbol_status_idx_8f05204b';
                  readonly prefix: 'position_symbol_status_idx';
                  readonly columns: readonly ['symbol', 'status'];
                  readonly unique: false;
                },
                {
                  readonly name: 'position_accountId_idx_cbfb3085';
                  readonly prefix: 'position_accountId_idx';
                  readonly columns: readonly ['accountId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'position';
                    readonly columns: readonly ['accountId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'demoAccount';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly trade: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly accountId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly orderId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly positionId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly symbol: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly side: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly quantity: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly entryPrice: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly exitPrice: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly realizedPnl: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly commission: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly openedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly closedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'trade_accountId_openedAt_idx_dfbcf78d';
                  readonly prefix: 'trade_accountId_openedAt_idx';
                  readonly columns: readonly ['accountId', 'openedAt'];
                  readonly unique: false;
                },
                {
                  readonly name: 'trade_accountId_idx_cbfb3085';
                  readonly prefix: 'trade_accountId_idx';
                  readonly columns: readonly ['accountId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'trade_orderId_idx_d284871b';
                  readonly prefix: 'trade_orderId_idx';
                  readonly columns: readonly ['orderId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'trade_positionId_idx_f0417710';
                  readonly prefix: 'trade_positionId_idx';
                  readonly columns: readonly ['positionId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'trade';
                    readonly columns: readonly ['accountId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'demoAccount';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'trade';
                    readonly columns: readonly ['orderId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'order';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'trade';
                    readonly columns: readonly ['positionId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'position';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly passwordHash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly fullName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'USER'>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly AccountStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ACTIVE', 'SUSPENDED', 'CLOSED'];
            };
            readonly OrderSide: {
              readonly kind: 'valueSet';
              readonly values: readonly ['BUY', 'SELL'];
            };
            readonly OrderStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PENDING', 'FILLED', 'REJECTED', 'CANCELLED'];
            };
            readonly OrderType: { readonly kind: 'valueSet'; readonly values: readonly ['MARKET'] };
            readonly PositionSide: {
              readonly kind: 'valueSet';
              readonly values: readonly ['LONG', 'SHORT'];
            };
            readonly PositionStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['OPEN', 'CLOSED'];
            };
            readonly UserRole: {
              readonly kind: 'valueSet';
              readonly values: readonly ['USER', 'ADMIN'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly user: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly demoAccount: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'DemoAccount';
    };
    readonly marketPrice: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'MarketPrice';
    };
    readonly order: { readonly namespace: 'public' & NamespaceId; readonly model: 'Order' };
    readonly position: { readonly namespace: 'public' & NamespaceId; readonly model: 'Position' };
    readonly trade: { readonly namespace: 'public' & NamespaceId; readonly model: 'Trade' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly DemoAccount: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly accountNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly currency: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly initialBalance: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly balance: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly equity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly orders: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Order';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['accountId'];
                };
              };
              readonly positions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Position';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['accountId'];
                };
              };
              readonly trades: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Trade';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['accountId'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'demoAccount';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'userId' };
                readonly accountNumber: { readonly column: 'accountNumber' };
                readonly currency: { readonly column: 'currency' };
                readonly initialBalance: { readonly column: 'initialBalance' };
                readonly balance: { readonly column: 'balance' };
                readonly equity: { readonly column: 'equity' };
                readonly status: { readonly column: 'status' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly MarketPrice: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly symbol: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly bid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly ask: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly last: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly source: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly timestamp: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'marketPrice';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly symbol: { readonly column: 'symbol' };
                readonly bid: { readonly column: 'bid' };
                readonly ask: { readonly column: 'ask' };
                readonly last: { readonly column: 'last' };
                readonly source: { readonly column: 'source' };
                readonly timestamp: { readonly column: 'timestamp' };
              };
            };
          };
          readonly Order: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly accountId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly symbol: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly side: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly orderType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly requestedPrice: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly executedPrice: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly commission: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly executedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly account: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DemoAccount';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['accountId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly trades: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Trade';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['orderId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'order';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly accountId: { readonly column: 'accountId' };
                readonly symbol: { readonly column: 'symbol' };
                readonly side: { readonly column: 'side' };
                readonly orderType: { readonly column: 'orderType' };
                readonly quantity: { readonly column: 'quantity' };
                readonly requestedPrice: { readonly column: 'requestedPrice' };
                readonly executedPrice: { readonly column: 'executedPrice' };
                readonly status: { readonly column: 'status' };
                readonly commission: { readonly column: 'commission' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly executedAt: { readonly column: 'executedAt' };
              };
            };
          };
          readonly Position: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly accountId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly symbol: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly side: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly averageEntryPrice: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly currentPrice: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly unrealizedPnl: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly openedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly closedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly account: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DemoAccount';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['accountId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly trades: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Trade';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['positionId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'position';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly accountId: { readonly column: 'accountId' };
                readonly symbol: { readonly column: 'symbol' };
                readonly side: { readonly column: 'side' };
                readonly quantity: { readonly column: 'quantity' };
                readonly averageEntryPrice: { readonly column: 'averageEntryPrice' };
                readonly currentPrice: { readonly column: 'currentPrice' };
                readonly unrealizedPnl: { readonly column: 'unrealizedPnl' };
                readonly status: { readonly column: 'status' };
                readonly openedAt: { readonly column: 'openedAt' };
                readonly closedAt: { readonly column: 'closedAt' };
              };
            };
          };
          readonly Trade: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly accountId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly orderId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly positionId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly symbol: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly side: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly entryPrice: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly exitPrice: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly realizedPnl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly commission: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly openedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly closedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly account: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DemoAccount';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['accountId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly order: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Order';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['orderId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly position: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Position';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['positionId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'trade';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly accountId: { readonly column: 'accountId' };
                readonly orderId: { readonly column: 'orderId' };
                readonly positionId: { readonly column: 'positionId' };
                readonly symbol: { readonly column: 'symbol' };
                readonly side: { readonly column: 'side' };
                readonly quantity: { readonly column: 'quantity' };
                readonly entryPrice: { readonly column: 'entryPrice' };
                readonly exitPrice: { readonly column: 'exitPrice' };
                readonly realizedPnl: { readonly column: 'realizedPnl' };
                readonly commission: { readonly column: 'commission' };
                readonly openedAt: { readonly column: 'openedAt' };
                readonly closedAt: { readonly column: 'closedAt' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fullName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly demoAccounts: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DemoAccount';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly passwordHash: { readonly column: 'passwordHash' };
                readonly fullName: { readonly column: 'fullName' };
                readonly role: { readonly column: 'role' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly UserRole: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'USER'; readonly value: 'USER' },
              { readonly name: 'ADMIN'; readonly value: 'ADMIN' },
            ];
          };
          readonly AccountStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ACTIVE'; readonly value: 'ACTIVE' },
              { readonly name: 'SUSPENDED'; readonly value: 'SUSPENDED' },
              { readonly name: 'CLOSED'; readonly value: 'CLOSED' },
            ];
          };
          readonly OrderSide: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'BUY'; readonly value: 'BUY' },
              { readonly name: 'SELL'; readonly value: 'SELL' },
            ];
          };
          readonly OrderType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [{ readonly name: 'MARKET'; readonly value: 'MARKET' }];
          };
          readonly OrderStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'FILLED'; readonly value: 'FILLED' },
              { readonly name: 'REJECTED'; readonly value: 'REJECTED' },
              { readonly name: 'CANCELLED'; readonly value: 'CANCELLED' },
            ];
          };
          readonly PositionSide: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'LONG'; readonly value: 'LONG' },
              { readonly name: 'SHORT'; readonly value: 'SHORT' },
            ];
          };
          readonly PositionStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'OPEN'; readonly value: 'OPEN' },
              { readonly name: 'CLOSED'; readonly value: 'CLOSED' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'demoAccount';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'demoAccount';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'marketPrice';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'order';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'position';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'trade';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'user';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'user';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
